### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by jamnut** [ajnsit/purescript-concur-starter#31]
I'm on macos Ventura 13.5 running npm version 9.6.7 and am getting this error.  I see that the latest changes are 3 years ago, does this mean that this repo doesn't work with the latest purescript?  (I'm running purs version 0.15.10)

npm ERR! code 1
npm ERR! path /Users/steveweeks/dev/PureScript/concur-starter/node_modules/purescript
npm ERR! command failed
npm ERR! command sh -c install-purescript --purs-ver=0.15.7
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module './promise'

**Comment by jamnut** [comment]
Some progress.  It looks like a versioning problem.  My purs, spago and parcel are all globally installed and the 'npm install' step installs conflicting versions.  If instead, I run:

- npm install react
- npm install update-browserslist-db@1.0.11
- npm install update-browserslist-db@latest
- spago build
- parcel dev/index.html --open

i get the following:
Server running at http://localhost:1234
🚨 Build failed.

Error: Expected content key b610778945a5a48d to exist

  Error: Expected content key b610778945a5a48d to exist
      at nullthrows (/usr/local/lib/node_modules/parcel/node_modules/nullthrows/nullthrows.js:7:15)
      at AssetGraph.getNodeIdByContentKey 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/graph/lib/ContentGraph.js:67:38)
      at /usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/SymbolPropagation.js:52:82
      at Array.map (<anonymous>)
      at propagateSymbols (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/SymbolPropagation.js:52:61)
      at AssetGraphBuilder.build 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:168:62)
      at async Object.run 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:60:37)
      at async RequestTracker.runRequest 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/RequestTracker.js:633:20)
      at async Object.run 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:103:11)
      at async RequestTracker.runRequest 
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/RequestTracker.js:633:20)

Any ideas on what to try next?

- -
